import type { FileNode } from './types';

export const initialFiles: FileNode[] = [
  {
    id: '1',
    name: 'Documents',
    type: 'folder',
    path: '/Documents',
    parentId: null,
    modifiedAt: '2023-10-01T10:00:00Z',
    size: 0,
  },
  {
    id: '2',
    name: 'Pictures',
    type: 'folder',
    path: '/Pictures',
    parentId: null,
    modifiedAt: '2023-10-01T11:00:00Z',
    size: 0,
  },
  {
    id: '3',
    name: 'project-brief.txt',
    type: 'text',
    path: '/Documents/project-brief.txt',
    parentId: '1',
    modifiedAt: '2023-10-02T14:30:00Z',
    size: 1536,
    content: 'FileSurfer Project Brief...\n\nCore Features:\n- File Listing\n- File Preview\n- File Management\n- Search Functionality\n- Webview optimization\n- AI-powered Suggest Tool',
  },
  {
    id: '4',
    name: 'vacation.jpg',
    type: 'image',
    path: '/Pictures/vacation.jpg',
    parentId: '2',
    modifiedAt: '2023-09-15T18:45:00Z',
    size: 2097152,
    url: 'https://picsum.photos/seed/4/1200/800',
  },
  {
    id: '5',
    name: 'logo.svg',
    type: 'image',
    path: '/logo.svg',
    parentId: null,
    modifiedAt: '2023-10-05T09:00:00Z',
    size: 5120,
    url: 'https://picsum.photos/seed/5/200/200',
  },
  {
    id: '6',
    name: 'Reports',
    type: 'folder',
    path: '/Documents/Reports',
    parentId: '1',
    modifiedAt: '2023-10-04T16:00:00Z',
    size: 0,
  },
  {
    id: '7',
    name: 'q3-report.pdf',
    type: 'pdf',
    path: '/Documents/Reports/q3-report.pdf',
    parentId: '6',
    modifiedAt: '2023-10-04T16:05:00Z',
    size: 5242880,
  },
  {
    id: '8',
    name: 'Family',
    type: 'folder',
    path: '/Pictures/Family',
    parentId: '2',
    modifiedAt: '2023-09-20T10:00:00Z',
    size: 0,
  },
  {
    id: '9',
    name: 'new-years.jpg',
    type: 'image',
    path: '/Pictures/Family/new-years.jpg',
    parentId: '8',
    modifiedAt: '2023-09-20T10:05:00Z',
    size: 3145728,
    url: 'https://picsum.photos/seed/9/1200/900'
  },
    {
    id: '10',
    name: 'index.html',
    type: 'text',
    path: '/index.html',
    parentId: null,
    modifiedAt: '2023-10-05T11:00:00Z',
    size: 1024,
    content: '<html><head><title>FileSurfer</title></head><body><h1>Welcome to FileSurfer!</h1></body></html>'
  },
];
